*Linear Algebra*

In [4]:
import numpy as np
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [5]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [6]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [7]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [9]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

size of an Object

In [10]:
# An integer in Python is > 24bytes
import sys
sys.getsizeof(1)

28

In [11]:
#Longs are even larger
sys.getsizeof(10**100)

72

In [12]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [13]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [14]:
np.dtype(float).itemsize

8

In [15]:
# A one-element list
sys.getsizeof([1])

64

In [16]:
# An array of one element in numpy
np.array([1]).nbytes

4

In [17]:
l = list(range(100000))

In [18]:
a = np.arange(100000)

In [22]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 982 µs


216474736

In [21]:
%time sum([x ** 2 for x in l])

CPU times: total: 0 ns
Wall time: 10 ms


333328333350000

In [24]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.linspace(0, 1, 20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [26]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])