In [1]:
import sys
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [8]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [9]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [10]:
a.dtype

dtype('int32')

In [11]:
b.dtype

dtype('float64')

In [13]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [14]:
c = np.array(['a', 'b', 'c'])

In [16]:
c.dtype

dtype('<U1')

In [15]:
d = np.array([{'a': 1}, sys])

In [17]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [27]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
A.shape

(2, 3)

In [19]:
A.ndim

2

In [20]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [21]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [22]:
B.shape

(2, 2, 3)

In [23]:
B.ndim

3

In [24]:
B.size

12

In [26]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.